### PR TITLE
[fix]: not return actual tree

### PR DESCRIPTION
**Pull request by GitScrum**

### CODE REVIEW

**Comment by GitScrum** [comment]
@revelt why you close ? tests failed :(

**Comment by revelt** [comment]
I'll look into this tonight properly, Travis sometimes gives false alerts, it's probably false alert

**Comment by GitScrum** [comment]
ok, if you have problem ping me and i help you.
Have nice day

**Comment by revelt** [comment]
hi Ivan,
I have a question. Inside the plugin, we took the `tree` and assigned the processed result into `tree[0]`. When testing, I checked what does `res` from the following code contain:

```js
return posthtml([plugin(options)])
    .process(html)
    .then((res) => {
```

And that `res` is an object, containing two keys, `html` (the old HTML), and `tree` which is parsed AST of the HTML, processed by plugin.

1. What's the point of having the original HTML contents under `html` key?
2. When testing I was apparently comparing desired code against the `html`, not `tree`, hence the test in Travis (and in general) were failing. In unit tests I'm going to switch to compare the contents of `tree`, but let me know if that's not a good idea.

cheers
Roy

**Comment by GitScrum** [comment]
Hi, i write step process:
1. `posthtml` get you string and parse -> 
  ```js
  [
    [you tree], // `tree[0]`
    api,
    options
  ]
  ```
2. call you plugin, you plugin render use `posthtml-render` -> out string and parse use `posthtml-parser` ->
  ```js
  [
    [you tree]
  ]
  ```  
  > :warning: *here you lost api and options*  

3. `posthtml` get you tree and render with default render options.

If it's not clear, let me know and I'll try to give your question more time. Thanks.

**Comment by GitScrum** [comment]
And you not need `posthtml-render` and `posthtml-parser` as `dependencies`. 
Use `tree.processor.constructor.parser` and `tree.processor.constructor.render`

**Comment by revelt** [comment]
Thank you! I'll look into this tonight.

**Pull request merged**
